services:
  backend:
    build:
      context: ./backend
    ports:
      - '3005:3000'
    depends_on:
      - server
    env_file:
      - ./backend/.env
    networks:
      - app-network
  server:
    build:
      context: ./server
    ports:
      - '8080:8080'
    network_mode: "host"
    env_file:
      - ./server/.env
   
networks:
  app-network:
    driver: bridge

