import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import "react-datepicker/dist/react-datepicker.css";
import { auth } from "@/lib/auth";
import AuthProvider from "./AuthProvider";
import ToasterProvider from "./ToasterProvider";
import { getGeneralSettings } from "./actions/actions";

// Root layout reads session via auth(); static prerender triggers Next.js 15
// workUnitAsyncStorage invariant errors on protected pages.
export const dynamic = "force-dynamic";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export async function generateMetadata(): Promise<Metadata> {
  const session = await auth();
  let generalSettings;
  if (session) {
    generalSettings = await getGeneralSettings(session);
  }

  return {
    title: generalSettings?.org_name ?? "Lurnic",
    description: "Generated by Nextrike",
    icons: {
      icon: generalSettings?.favicon ?? "/favicon.svg",
    },
  };
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <body className={`${geistSans.className} antialiased`}>
        <ToasterProvider />
        <AuthProvider session={session}>{children}</AuthProvider>
      </body>
    </html>
  );
}
